# Generated by Django 5.0.6 on 2024-05-12 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'in_progress'), ('DEFERRED', 'defer'), ('COMPLETED', 'completed')], default='TODO', max_length=11, verbose_name='completed')),
                ('priority', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='low', max_length=6, verbose_name='priority')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('updated_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='updated timestamp')),
                ('created_timestamp', models.DateTimeField(auto_now=True, verbose_name='created timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
