# Generated by Django 5.0.6 on 2024-05-13 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='medium', max_length=6, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'in_progress'), ('DEFERRED', 'defer'), ('COMPLETED', 'completed')], default='TODO', max_length=12, verbose_name='completed'),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'in_progress'), ('DEFERRED', 'defer'), ('COMPLETED', 'completed')], default='TODO', max_length=12, verbose_name='completed')),
                ('priority', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='medium', max_length=6, verbose_name='priority')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='deadline')),
                ('updated_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='updated timestamp')),
                ('created_timestamp', models.DateTimeField(auto_now=True, verbose_name='created timestamp')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='tasks.task')),
            ],
            options={
                'verbose_name': 'SubTask',
                'verbose_name_plural': 'SubTasks',
            },
        ),
    ]
