# Generated by Django 5.0.6 on 2024-05-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_deadline_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Add this field to the body of your request when creating sub-comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='low', max_length=6, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'in_progress'), ('DEFERRED', 'defer'), ('COMPLETED', 'completed')], default='TODO', max_length=11, verbose_name='completed'),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
